# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{ 
  "title": "Клюквs",
  "description": "Какая-то клюкdf"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/7/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/9/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=груша
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Гагарина 127",
  "positions": [
    { 
      "product": 1,
      "quantity": 500,
      "price": 90.05
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/126/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 1000,
      "price": 130.80
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json
    # {
    #   "product": 3,
    #   "quantity": 243,
    #   "price": 145
    # }